### ISSUE TITLE
Problem with test code

### ISSUE THREAD

**Issue by Knight1** [karolyi/py3-ecrterm#2]
Any Ideas?

With Python 2.7.13
```
root@raspberrypi:~/py3-ecrterm# python2 test.py
Traceback (most recent call last):
  File "test.py", line 6, in <module>
    from ecrterm.ecr import ECR, ecr_log
  File "/root/py3-ecrterm/ecrterm/ecr.py", line 12, in <module>
    from ecrterm.common import TERMINAL_STATUS_CODES
  File "/root/py3-ecrterm/ecrterm/common.py", line 93
SyntaxError: Non-ASCII character '\xe2' in file /root/py3-ecrterm/ecrterm/common.py on line 93, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
```
With python 3.5.3
```
root@raspberrypi:~/py3-ecrterm# python3 test.py
True
Traceback (most recent call last):
  File "/root/py3-ecrterm/ecrterm/conv.py", line 112, in toBytes
    '2s' * (len(packedstring) // 2), packedstring), [])
struct.error: unpack requires a bytes object of length 4

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test.py", line 24, in <module>
    ecr_controls_admin=True))
  File "/root/py3-ecrterm/ecrterm/ecr.py", line 186, in register
    ret = self.transmit(Registration(**kwargs))
  File "/root/py3-ecrterm/ecrterm/ecr.py", line 373, in transmit
    transmission = self.transmitter.transmit(packet)
  File "/root/py3-ecrterm/ecrterm/transmission/_transmission.py", line 92, in transmit
    ret = self._transmit(packet, self.last_history)
  File "/root/py3-ecrterm/ecrterm/transmission/_transmission.py", line 57, in _transmit
    success, response = self.transport.send(packet)
  File "/root/py3-ecrterm/ecrterm/transmission/transport_socket.py", line 106, in send
    to_send = bytes(apdu.to_list())
  File "/root/py3-ecrterm/ecrterm/packets/apdu.py", line 182, in to_list
    return [self.cmd_class, self.cmd_instr or 0] + self.data
  File "/root/py3-ecrterm/ecrterm/packets/apdu.py", line 171, in get_data
    data += self.enrich_fixed()
  File "/root/py3-ecrterm/ecrterm/packets/apdu.py", line 154, in enrich_fixed
    val = toBytes(val)
  File "/root/py3-ecrterm/ecrterm/conv.py", line 114, in toBytes
    raise TypeError('not a string representing a list of bytes')
TypeError: not a string representing a list of bytes
```

**Comment by karolyi** [comment]
what test is this? can you provide the test file?

also mind you, this module is py3 only.

**Comment by karolyi** [comment]
closing for inactivity

**Comment by bwurst** [comment]
I stumbled upon this issue report because I had the same error message on Python 3.

Please let me add my error here: I put in a PIN number / password with 5 chars (12345) instead of 6 chars. This was the issue. It worked when I put in 123456.

Unsure if this should be catched in the code but I wanted to add the reason here if someone else comes here for this error.
